# Generated by Django 6.0.4 on 2026-04-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('caseid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('officerid', models.IntegerField()),
                ('firid', models.IntegerField(blank=True, null=True)),
                ('case_date', models.DateField()),
                ('open_date', models.DateField()),
                ('close_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cases',
                'managed': False,
            },
        ),
    ]
