# Generated by Django 6.0.5 on 2026-05-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_details',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='contact_details',
            name='password',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
       
    ]
